### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by sirselim** [cvdelannoy/baseLess#2]
Very interesting tool and preprint.

In your abstract you state "translating the electrical signal it outputs into a sequence of bases still requires high-end computer hardware" - what is the definition of high-end computer hardware that you are using here?

**Comment by cvdelannoy** [comment]
Thanks!

I'm on a laptop I would consider high-end (~€2000, 8-core 3GHz CPU, Nvidia T500 GPU, 16GB RAM) and on a set of 1000 16S reads I barely hit the maximum throughput for a MinION at 225 kb/s with guppy (Version 6.2.1+6588110) in fast mode. On second thought this could have been worded more carefully, maybe high-end laptop would have been a better choice. Would you agree?

Thanks a lot for all the collected resources on running on the Jetson, btw! I'm sad that I couldn't get the Jetson GPU to work in the end, as stated in the paper, but your notes helped a bunch.

**Comment by sirselim** [comment]
Thanks for the clarification. It's more semantics I guess and I think it's one of those things like the accuracy "issues" that always get thrown about that just really aren't true anymore. If FAST basecalling is the goal then a $399 USD Jetson Xavier NX is more than capable of keeping up with a MinION in fast mode - is that high-end computer hardware, I'm not sure (not by my definition) but I think a bit more clarification around what one is defining as high-end is useful for readers as it can mean many different things to different people. In terms of running the HAC and SUP models, something like the new Jetson Orin AGX will easily achieve those sorts of speeds. Additionally, these days you can get fairly entry level gaming laptops that are more than capable of keeping up with FAST basecalling, and even HAC, so I don't think the high-end "stigma" is as big of an issue as it used to be. But this is just my 2 cents. ;)

In terms of the T500 GPU, it is Turing based but it's held back by 2GB of GPU RAM. The Xavier NX and AGX are running Volta GPUs with less CUDA cores than your T500 but they have the advantage of sharing decently fast system RAM between the GPU and rest of the system. That's why the 384 CUDA core NX with 8GB of shared RAM is able to perform FAST calling in real-time.

I'm glad all those notes etc were useful. Unfortunately you were always going to struggle with the Jetson Nano for basecalling, due to the fact that it has a Maxwell based GPU which doesn't have the CUDA compute version able to support Guppy out of the box. It is possible to get Guppy working on the Nano, it requires developer access to the Guppy source and some additional compilation flags. I have a friend that has several Nano's running Guppy and it seems to hold up decently for Flongle levels of data. Before I joined Nanopore I was playing with sequencing on the Nano (it runs MinKNOW just fine) and then using free GPU enabled Google Colab notebooks for near real-time cloud basecalling. It worked really nicely and I always thought it would be a good cheap options for teaching labs, low cost entry etc.

Thanks again for the really interesting manuscript, some really nice work and it's exciting seeing the accessibility and cost of entry lowered for people, I believe this is the heart of the MinION technology. I'd love to chat some time about an idea that I had recently that fit's quite nicely within the framework of what you've done here.

EDIT: thought this GPU benchmarking might be of interest if you hadn't come across it before: https://github.com/sirselim/guppy_parameter_optimiser/blob/main/gpu_basecalling_benchmarking.md

**Comment by cvdelannoy** [comment]
Thanks, had not seen the benchmark before, very useful!

That's a very thorough description of resource requirements, I suppose you're right that on appropriate hardware base calling has become more efficient than is generally believed. I'll try to find some descriptor that better captures the current state of art for the paper we're submitting. :) 

I'd very much like to chat about your idea! Could you send me an email at c.v.delannoy[at]tudelft.nl or find me on twitter (@cvdelannoy) so we discuss further or set up a call?
